# Generated by Django 3.1 on 2020-09-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20200916_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='num_verified',
            field=models.BooleanField(default=False, null=True, verbose_name='Verified'),
        ),
    ]
